### ISSUE TITLE
UPM.SharpZipLib on OpenUPM

### ISSUE THREAD

**Issue by favoyang** [karasusan/UPM.SharpZipLib#1]
Hi @karasusan,

Thanks for creating the project to pack SharpZipLib as a package. I'm the creator of [OpenUPM](https://openupm.com), a public upm registry with automatic build pipelines that publish new package bundle based on valid git tags. You can read [the announcement](https://www.patreon.com/posts/openupm-beta-is-32544176) to get the basic idea, so far it hosts 80+ packages as of December 2019.

I would like to [include this package](https://openupm.com/packages/add/) if you could make a [GitHub Release](https://github.com/karasusan/UPM.SharpZipLib/releases) for v1.0.0

**Comment by piksel** [comment]
There is an official SharpZipLib package on OpenUPM at https://openupm.com/packages/org.icsharpcode.sharpziplib/

**Comment by favoyang** [comment]
Oh, it's a very old thread. Thank you for the reply.
